runtime: php55
api_version: 1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

inbound_services:
- warmup

handlers:
- url: /
  script: login.php

- url: /css
  static_dir: css

- url: /css
  static_dir: png

- url: /js
  static_dir: js
  
- url: /(.+\.php)$
  script: \1

